### ISSUE TITLE
Support for older "Browse for Folder" dialog

### ISSUE THREAD

**Issue by letmeindude** [skygate2012/ReplaceBrowseForFolder#1]
Most apps I use have older "Browse for Folder" dialog, which ReplaceBrowseForFolder doesn't detect.
For example, SnailSync https://www.softpedia.com/get/System/File-Management/SnailSync.shtml

Is it possible to add support for older "Browse for Folder" dialog?

**Comment by skygate2012** [comment]
Hi, I tested the program and it seems we can get the list items from memory. One thing though, is that it would be hard to know for sure that this is a "Browse For Folder" dialog. The ListView control doesn't have a unique name. Currently I'm identifying the dialogs by a unique telltale name that is "SHBrowseForFolder ShellNameSpace Control1", of which I suppose is a rather newer addition upon inspecting the program you mentioned. I don't want to match the dialogs by window title as that's locale-dependent.

Perhaps you can help me with this. Can you run this AutoHotkey script to collect all the control names of all the apps you use that have older dialogs, to see if we can find a workable pattern? It saves the list to clipboard by pressing F1.
```
#Requires AutoHotkey v1.1.33+
#NoEnv
#SingleInstance Force

F1::
WinGetClass WinClass, A
WinGet, CtlList, ControlList, A
Report := "Window: " WinClass "`n`nControls:`n" CtlList
Clipboard := Report
Tooltip % Report
SetTimer, ToolTipOff, -1000
return

ToolTipOff:
ToolTip
return
```

**Comment by letmeindude** [comment]
On my Windows 10 all undetected apps produced this:

Window: #32770

Controls:
Static1
Static2
SysTreeView321
Button1
Button2

**Comment by skygate2012** [comment]
Added f865924be2b27c0bfa672ff4e512fd6a66f7d1d6

**Comment by letmeindude** [comment]
Amazing, thank you very much, now it's perfect.
